MailAI: src.authapp.tests.SignupFlowTests Class Reference
src.authapp.tests.SignupFlowTests Class Reference
Public Member Functions
test_signup_form_saves_profile_with_encrypted_password (self)
test_signup_view_redirects_after_success (self)
Protected Member Functions
dict _valid_formdata (self)
Detailed Description
1) 폼 레벨 : 암호화 함수가 호출되고 결과가 UserProfile 에 저장되는지
2) 뷰  레벨 :                       정상 가입 후 /login 으로 리다이렉트 되는지
Definition at line 11 of file tests.py.
Member Function Documentation
_valid_formdata()
dict src.authapp.tests.SignupFlowTests._valid_formdata (self) protected
Definition at line 17 of file tests.py.
Referenced by src.authapp.tests.SignupFlowTests.test_signup_form_saves_profile_with_encrypted_password(), and src.authapp.tests.SignupFlowTests.test_signup_view_redirects_after_success().
test_signup_form_saves_profile_with_encrypted_password()
src.authapp.tests.SignupFlowTests.test_signup_form_saves_profile_with_encrypted_password (self)
Definition at line 28 of file tests.py.
References src.authapp.tests.SignupFlowTests._valid_formdata().
test_signup_view_redirects_after_success()
src.authapp.tests.SignupFlowTests.test_signup_view_redirects_after_success (self)
Definition at line 40 of file tests.py.
References src.authapp.tests.SignupFlowTests._valid_formdata().
The documentation for this class was generated from the following file:
src/authapp/tests.py