MailAI: skkumail.src.utils.mailai_smtp Namespace Reference
skkumail.src.utils.mailai_smtp Namespace Reference
Functions
def generate_mail_content (name, relation, style, text)
def send_mail (user_id, recipient, subject, message)
Function Documentation
generate_mail_content()
def skkumail.src.utils.mailai_smtp.generate_mail_content (name, relation, style, text)
Definition at line 8 of file mailai_smtp.py.
Referenced by skkumail.src.wmailapp.views.mail_process_view().
send_mail()
def skkumail.src.utils.mailai_smtp.send_mail (user_id, recipient, subject, message)
Definition at line 14 of file mailai_smtp.py.
References skkumail.src.authapp.smtp_crypto.decrypt_smtp_password().
Referenced by skkumail.src.wmailapp.views.mail_process_view().