MailAI: src.wmailapp.utils Namespace Reference
src.wmailapp.utils Namespace Reference
Functions
def generate_mail_content (name, relation, style, text)
def send_mail (recipient, subject, message)
def decrypt_password (encrypted_password)
def send_mail (user_id, recipient, subject, message)
Function Documentation
decrypt_password()
def src.wmailapp.utils.decrypt_password (encrypted_password)
Definition at line 19 of file utils.py.
Referenced by src.wmailapp.utils.send_mail().
generate_mail_content()
def src.wmailapp.utils.generate_mail_content (name, relation, style, text)
Definition at line 3 of file utils.py.
Referenced by src.wmailapp.views.mail_process_view().
send_mail() [1/2]
def src.wmailapp.utils.send_mail (recipient, subject, message)
Definition at line 9 of file utils.py.
Referenced by src.wmailapp.views.mail_process_view(), and src.wmailapp.utils.send_mail().
send_mail() [2/2]
def src.wmailapp.utils.send_mail (user_id, recipient, subject, message)
Definition at line 25 of file utils.py.
References src.wmailapp.utils.decrypt_password(), and src.wmailapp.utils.send_mail().