MailAI: src.rmailapp.views Namespace Reference
src.rmailapp.views Namespace Reference
Functions
str translate_email (str body)
str llm_translate_email (str body)
str summarize_email (str body)
str bert_summarize_email (str body)
extract_keyword_email (body)
email_detail (request, email_id)
show_emails (request)
handle_emails (request)
Function Documentation
bert_summarize_email()
str src.rmailapp.views.bert_summarize_email (str body)
Definition at line 40 of file views.py.
Referenced by src.rmailapp.views.email_detail().
email_detail()
src.rmailapp.views.email_detail (request, email_id)
Definition at line 56 of file views.py.
References src.rmailapp.views.bert_summarize_email(), src.rmailapp.views.extract_keyword_email(), src.rmailapp.views.llm_translate_email(), src.rmailapp.views.summarize_email(), and src.rmailapp.views.translate_email().
extract_keyword_email()
src.rmailapp.views.extract_keyword_email (body)
Definition at line 47 of file views.py.
Referenced by src.rmailapp.views.email_detail().
handle_emails()
src.rmailapp.views.handle_emails (request)
Definition at line 104 of file views.py.
llm_translate_email()
str src.rmailapp.views.llm_translate_email (str body)
Definition at line 26 of file views.py.
Referenced by src.rmailapp.views.email_detail().
show_emails()
src.rmailapp.views.show_emails (request)
Definition at line 84 of file views.py.
summarize_email()
str src.rmailapp.views.summarize_email (str body)
Definition at line 33 of file views.py.
Referenced by src.rmailapp.views.email_detail().
translate_email()
str src.rmailapp.views.translate_email (str body)
Definition at line 19 of file views.py.
Referenced by src.rmailapp.views.email_detail().