MailAI: src.comm.mailai_compatibility Namespace Reference
src.comm.mailai_compatibility Namespace Reference
Classes
class ServerTypeException
Functions
str email_to_server_type (str email)
str get_smtp_server (str server_type)
str get_imap_server (str server_type)
Variables
string OUTLOOK = 'outlook'
string GMAIL = 'gmail'
string NAVER = 'naver'
dictionary SMTP_SERVERS
dictionary IMAP_SERVERS
Function Documentation
email_to_server_type()
str src.comm.mailai_compatibility.email_to_server_type (str email)
Definition at line 24 of file mailai_compatibility.py.
Referenced by src.comm.mailai_imap.fetch_emails(), src.comm.mailai_compatibility.get_imap_server(), src.comm.mailai_smtp.send_mail(), and src.comm.mailai_smtp.verify_smtp_credentials().
get_imap_server()
str src.comm.mailai_compatibility.get_imap_server (str server_type)
Definition at line 41 of file mailai_compatibility.py.
References src.comm.mailai_compatibility.email_to_server_type(), and src.comm.mailai_compatibility.get_smtp_server().
Referenced by src.comm.mailai_imap.fetch_emails().
get_smtp_server()
str src.comm.mailai_compatibility.get_smtp_server (str server_type)
Definition at line 37 of file mailai_compatibility.py.
Referenced by src.comm.mailai_compatibility.get_imap_server(), src.comm.mailai_smtp.send_mail(), and src.comm.mailai_smtp.verify_smtp_credentials().
Variable Documentation
GMAIL
string src.comm.mailai_compatibility.GMAIL = 'gmail'
Definition at line 2 of file mailai_compatibility.py.
IMAP_SERVERS
dictionary src.comm.mailai_compatibility.IMAP_SERVERS
Initial value:
 =  {
     OUTLOOK: 'outlook.office365.com',
     GMAIL: 'imap.gmail.com',
     NAVER: 'imap.worksmobile.com'
 }
Definition at line 11 of file mailai_compatibility.py.
NAVER
string src.comm.mailai_compatibility.NAVER = 'naver'
Definition at line 3 of file mailai_compatibility.py.
OUTLOOK
string src.comm.mailai_compatibility.OUTLOOK = 'outlook'
Definition at line 1 of file mailai_compatibility.py.
SMTP_SERVERS
dictionary src.comm.mailai_compatibility.SMTP_SERVERS
Initial value:
 =  {
     OUTLOOK: 'smtp.office365.com',
     GMAIL: 'smtp.gmail.com',
     NAVER: 'smtp.worksmobile.com'
 }
Definition at line 5 of file mailai_compatibility.py.