MailAI: skkumail.src.authapp.views Namespace Reference
skkumail.src.authapp.views Namespace Reference
Functions
def index (request)
def user_signup (request)
def user_login (request)
def user_logout (request)
def delete_account (request)
Function Documentation
delete_account()
def skkumail.src.authapp.views.delete_account (request)
Definition at line 70 of file views.py.
index()
def skkumail.src.authapp.views.index (request)
Definition at line 15 of file views.py.
user_login()
def skkumail.src.authapp.views.user_login (request)
Definition at line 41 of file views.py.
user_logout()
def skkumail.src.authapp.views.user_logout (request)
Definition at line 63 of file views.py.
user_signup()
def skkumail.src.authapp.views.user_signup (request)
Definition at line 21 of file views.py.
References skkumail.src.authapp.smtp_crypto.decrypt_smtp_password(), skkumail.src.authapp.smtp_crypto.encrypt_smtp_password(), and skkumail.src.authapp.signup_tools.verify_smtp_credentials().