MailAI: src.comm.mailai_bert Namespace Reference
src.comm.mailai_bert Namespace Reference
Functions
truncate_for_bert (text, max_length=1024)
list extract_n_keywords (str text, int num_keywords)
str extract_keywords (str text)
summarize (str text)
Function Documentation
extract_keywords()
str src.comm.mailai_bert.extract_keywords (str text)
Definition at line 25 of file mailai_bert.py.
References src.comm.mailai_bert.extract_n_keywords(), and src.comm.mailai_bert.truncate_for_bert().
extract_n_keywords()
list src.comm.mailai_bert.extract_n_keywords (str text, int num_keywords)
Definition at line 15 of file mailai_bert.py.
References src.comm.mailai_bert.truncate_for_bert().
Referenced by src.comm.mailai_bert.extract_keywords().
summarize()
src.comm.mailai_bert.summarize (str text)
Definition at line 65 of file mailai_bert.py.
References src.comm.mailai_bert.truncate_for_bert().
truncate_for_bert()
src.comm.mailai_bert.truncate_for_bert (text, max_length = 1024)
Definition at line 6 of file mailai_bert.py.
Referenced by src.comm.mailai_bert.extract_keywords(), src.comm.mailai_bert.extract_n_keywords(), and src.comm.mailai_bert.summarize().