MailAI: src.comm.mailai_imap Namespace Reference
src.comm.mailai_imap Namespace Reference
Functions
bool fetch_emails (int user_id, int max_emails=500)
Variables
logger = logging.getLogger(__name__)
Function Documentation
fetch_emails()
bool src.comm.mailai_imap.fetch_emails (int user_id, int max_emails = 500)
Definition at line 19 of file mailai_imap.py.
References src.comm.smtp_crypto.decrypt_smtp_password(), and src.comm.mailai_base64.process_email_to_include_base64_images().
Referenced by src.rmailapp.views.handle_emails().
Variable Documentation
logger
src.comm.mailai_imap.logger = logging.getLogger(__name__)
Definition at line 16 of file mailai_imap.py.