MailAI: src.comm.mailai_gpt Namespace Reference
src.comm.mailai_gpt Namespace Reference
Functions
str get_mail_content_generator_prompt (str user_id, str name, str relation, str style, str text)
str get_mail_title_generator_prompt (str content)
str generate_mail_title (str content)
str generate_mail_content (str user_id, str name, str relation, str style, str text)
str get_summarize_prompt (str text)
str summarize (str text)
str get_translator_prompt (str text, str target_language)
str translate (str text)
Variables
openai_api_key = settings.OPENAI_API_KEY
openai_model = settings.OPENAI_MODEL
dictionary headers
string url = "https://api.openai.com/v1/chat/completions"
dictionary system_role_content
dictionary system_role_title
dictionary system_role_summarize
dictionary system_role_translate
Function Documentation
generate_mail_content()
str src.comm.mailai_gpt.generate_mail_content (str user_id, str name, str relation, str style, str text)
Definition at line 82 of file mailai_gpt.py.
References src.comm.mailai_gpt.get_mail_content_generator_prompt().
Referenced by src.wmailapp.views.mail_process_view().
generate_mail_title()
str src.comm.mailai_gpt.generate_mail_title (str content)
Definition at line 66 of file mailai_gpt.py.
References src.comm.mailai_gpt.get_mail_title_generator_prompt().
Referenced by src.wmailapp.views.mail_process_view().
get_mail_content_generator_prompt()
str src.comm.mailai_gpt.get_mail_content_generator_prompt (str user_id, str name, str relation, str style, str text)
Definition at line 35 of file mailai_gpt.py.
Referenced by src.comm.mailai_gpt.generate_mail_content().
get_mail_title_generator_prompt()
str src.comm.mailai_gpt.get_mail_title_generator_prompt (str content)
Definition at line 54 of file mailai_gpt.py.
Referenced by src.comm.mailai_gpt.generate_mail_title().
get_summarize_prompt()
str src.comm.mailai_gpt.get_summarize_prompt (str text)
Definition at line 98 of file mailai_gpt.py.
Referenced by src.comm.mailai_gpt.summarize().
get_translator_prompt()
str src.comm.mailai_gpt.get_translator_prompt (str text, str target_language)
Definition at line 128 of file mailai_gpt.py.
Referenced by src.comm.mailai_gpt.translate().
summarize()
str src.comm.mailai_gpt.summarize (str text)
Definition at line 111 of file mailai_gpt.py.
References src.comm.mailai_gpt.get_summarize_prompt().
translate()
str src.comm.mailai_gpt.translate (str text)
Definition at line 142 of file mailai_gpt.py.
References src.comm.mailai_gpt.get_translator_prompt().
Variable Documentation
headers
dictionary src.comm.mailai_gpt.headers
Initial value:
 =  {
     "Content-Type": "application/json",
     "Authorization": f"Bearer {openai_api_key}"
 }
Definition at line 7 of file mailai_gpt.py.
openai_api_key
src.comm.mailai_gpt.openai_api_key = settings.OPENAI_API_KEY
Definition at line 5 of file mailai_gpt.py.
openai_model
src.comm.mailai_gpt.openai_model = settings.OPENAI_MODEL
Definition at line 6 of file mailai_gpt.py.
system_role_content
dictionary src.comm.mailai_gpt.system_role_content
Initial value:
 =  {
     "role": "system",
     "content": "You are a GPT-based assistant tasked with writing an email. Do not add 'Subject:' or somethings."
 }
Definition at line 13 of file mailai_gpt.py.
system_role_summarize
dictionary src.comm.mailai_gpt.system_role_summarize
Initial value:
 =  {
     "role": "system",
     "content": "You are a GPT-based assistant specialized in summarize email contents."
 }
Definition at line 24 of file mailai_gpt.py.
system_role_title
dictionary src.comm.mailai_gpt.system_role_title
Initial value:
 =  {
     "role": "system",
     "content": "You are a GPT-based assistant specialized in creating professional email subject lines."
 }
Definition at line 19 of file mailai_gpt.py.
system_role_translate
dictionary src.comm.mailai_gpt.system_role_translate
Initial value:
 =  {
     "role": "system",
     "content": f"You are a GPT-based assistant specialized in translating email."
 }
Definition at line 29 of file mailai_gpt.py.
url
string src.comm.mailai_gpt.url = "https://api.openai.com/v1/chat/completions"
Definition at line 11 of file mailai_gpt.py.