MailAI: src.authapp.views Namespace Reference
src.authapp.views Namespace Reference
Functions
def index (request)
def user_signup (request)
def user_login (request)
def user_logout (request)
def delete_account (request)
Function Documentation
delete_account()
def src.authapp.views.delete_account (request)
Definition at line 68 of file views.py.
index()
def src.authapp.views.index (request)
Definition at line 15 of file views.py.
user_login()
def src.authapp.views.user_login (request)
Definition at line 41 of file views.py.
user_logout()
def src.authapp.views.user_logout (request)
Definition at line 61 of file views.py.
user_signup()
def src.authapp.views.user_signup (request)
Definition at line 21 of file views.py.
References src.comm.smtp_crypto.decrypt_smtp_password(), src.comm.smtp_crypto.encrypt_smtp_password(), and src.comm.mailai_smtp.verify_smtp_credentials().