MailAI: mailai.src.authapp.smtp_crypto Namespace Reference
mailai.src.authapp.smtp_crypto Namespace Reference
Functions
def encrypt_smtp_password (password)
def decrypt_smtp_password (encrypted_password)
Variables
fernet = Fernet(settings.DJANGO_CRYPTOGRAPHY_KEY.encode())
Function Documentation
decrypt_smtp_password()
def mailai.src.authapp.smtp_crypto.decrypt_smtp_password (encrypted_password)
Decrypt the SMTP password.
Definition at line 13 of file smtp_crypto.py.
Referenced by mailai.src.comm.mailai_smtp.send_mail(), and mailai.src.authapp.views.user_signup().
encrypt_smtp_password()
def mailai.src.authapp.smtp_crypto.encrypt_smtp_password (password)
Encrypt the SMTP password.
Definition at line 8 of file smtp_crypto.py.
Referenced by mailai.src.authapp.views.user_signup().
Variable Documentation
fernet
mailai.src.authapp.smtp_crypto.fernet = Fernet(settings.DJANGO_CRYPTOGRAPHY_KEY.encode())
Definition at line 5 of file smtp_crypto.py.