MailAI: mailai.src.comm.mailai_gpt Namespace Reference
mailai.src.comm.mailai_gpt Namespace Reference
Functions
str get_mail_content_generator_prompt (str name, str relation, str style, str text)
str get_mail_title_generator_prompt (str content)
str generate_mail_title (str content)
def generate_mail_content (name, relation, style, text)
Variables
openai_api_key = settings.OPENAI_API_KEY
openai_model = settings.OPENAI_MODEL
dictionary headers
string url = "https://api.openai.com/v1/chat/completions"
dictionary system_role_content
dictionary system_role_title
Function Documentation
generate_mail_content()
def mailai.src.comm.mailai_gpt.generate_mail_content (name, relation, style, text)
Definition at line 57 of file mailai_gpt.py.
References mailai.src.comm.mailai_gpt.get_mail_content_generator_prompt().
Referenced by mailai.src.wmailapp.views.mail_process_view().
generate_mail_title()
str mailai.src.comm.mailai_gpt.generate_mail_title (str content)
Definition at line 40 of file mailai_gpt.py.
References mailai.src.comm.mailai_gpt.get_mail_title_generator_prompt().
Referenced by mailai.src.wmailapp.views.mail_process_view().
get_mail_content_generator_prompt()
str mailai.src.comm.mailai_gpt.get_mail_content_generator_prompt (str name, str relation, str style, str text)
Definition at line 30 of file mailai_gpt.py.
Referenced by mailai.src.comm.mailai_gpt.generate_mail_content().
get_mail_title_generator_prompt()
str mailai.src.comm.mailai_gpt.get_mail_title_generator_prompt (str content)
Definition at line 37 of file mailai_gpt.py.
Referenced by mailai.src.comm.mailai_gpt.generate_mail_title().
Variable Documentation
headers
dictionary mailai.src.comm.mailai_gpt.headers
Initial value:
 =  {
     "Content-Type": "application/json",
     "Authorization": f"Bearer {openai_api_key}"
 }
Definition at line 7 of file mailai_gpt.py.
openai_api_key
mailai.src.comm.mailai_gpt.openai_api_key = settings.OPENAI_API_KEY
Definition at line 5 of file mailai_gpt.py.
openai_model
mailai.src.comm.mailai_gpt.openai_model = settings.OPENAI_MODEL
Definition at line 6 of file mailai_gpt.py.
system_role_content
dictionary mailai.src.comm.mailai_gpt.system_role_content
Initial value:
 =  {
     "role": "system",
     "content": "You are an expert in crafting professional business emails. Your task is to compose emails that are "
                "clear, concise, and appropriate for a business setting. Focus solely on the email body, ensuring it "
                "directly addresses the given points. Avoid any superfluous language, summaries, greetings, "
                "or sign-offs. you must make it plane text with new proper new lines and indents format so that it can "
                "handled with mail server. You must add Dear .. and at the end Best Regards, .."
 }
Definition at line 12 of file mailai_gpt.py.
system_role_title
dictionary mailai.src.comm.mailai_gpt.system_role_title
Initial value:
 =  {
     "role": "system",
     "content": "You are an expert in crafting professional business emails. Your task is to cdy, ensuring it directly "
                "addresses the given points. Avoid any superfluous language, summaries, greetings, or sign-offs. "
                "emails that are clear, concise, and appropriate for a business setting. Focus solely on the email "
                "subject that will be used in smtp email message."
 }
Definition at line 21 of file mailai_gpt.py.
url
string mailai.src.comm.mailai_gpt.url = "https://api.openai.com/v1/chat/completions"
Definition at line 11 of file mailai_gpt.py.