MailAI: src.comm.mailai_base64 Namespace Reference
src.comm.mailai_base64 Namespace Reference
Functions
process_email_to_include_base64_images (email_message)
BeautifulSoup text_to_beautiful_soup (str text)
str modify_base64_encoded_text_content (str text, Callable[[str], str] modification_function)
str get_combined_body (str body1, str body2, str description)
Function Documentation
get_combined_body()
str src.comm.mailai_base64.get_combined_body (str body1, str body2, str description)
Definition at line 74 of file mailai_base64.py.
References src.comm.mailai_base64.text_to_beautiful_soup().
modify_base64_encoded_text_content()
str src.comm.mailai_base64.modify_base64_encoded_text_content (str text, Callable[[str], str] modification_function)
Definition at line 32 of file mailai_base64.py.
References src.comm.mailai_base64.text_to_beautiful_soup().
process_email_to_include_base64_images()
src.comm.mailai_base64.process_email_to_include_base64_images (email_message)
Definition at line 8 of file mailai_base64.py.
text_to_beautiful_soup()
BeautifulSoup src.comm.mailai_base64.text_to_beautiful_soup (str text)
Definition at line 24 of file mailai_base64.py.
Referenced by src.comm.mailai_base64.get_combined_body(), and src.comm.mailai_base64.modify_base64_encoded_text_content().